export const USER_SET_LOADING= "USER_SET_LOADING";
export const USER_SET_LOADED_USER = "USER_SET_LOADED_USER";
export const USER_SET_REGISTER_SUCCESS = "USER_SET_REGISTER_SUCCESS";
export const USER_SET_LOGIN_SUCCESS = "USER_SET_LOGIN_SUCCESS";
export const USER_SET_LOGOUT_USER = "USER_SET_LOGOUT_USER";
export const USER_SET_AUTH_ERROR = "USER_SET_AUTH_ERROR";
