export const emptyChannelDraft = {
    id_tbcd: '',
    id_suz: '',
    id_oss: '',
    id_cms: '',
    client: '',
    service: '',
    service_size: null,
    city: '',
    street: '',
    home: '',
    add_info: '',
    contact: '',
    status: "РЕЗЕРВ",
    date: new Date(),
    note: "",
    rd_sr: "",
    channel_pe: null,
    channel_pe_port: "",
    channel_vid: "",
    zabbix: "",
    zabbix_avail: "",
    channel_region: 'crimea',
    channel_acc_stop: [{acc_stop: "", acc_port: "", acc_ip_mng: "", acc_model: "", acc_sn: "", acc_mac: "",  withStop: false}],
    channel_agg_stop: [{agg_stop: '', agg_port: '', withStop: false}]
}
